var GAME_LEVELS = [
  ["                                          ",
   "                                          ",
   " @                                        ",
   "xxxxxxxxx                                 ",
   "xxxxxxxxx                                 ",
   "xxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxx",
   "                                          ",
   "                                          ",
   "                                          ",
   "                                          ",
   "xxxxxxxxxxxxxxxxjjjjjjjjjjj    !!!!!!!!!!!",
   "                                          ",
   "                                          ",
   "                                          ",
   "              m m m         l             ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                          ",
   "                                          ",
   "                                          ",
   "                                          ",
   "xxxxxxxxxxjjjj!!!!!!!!!!!      l          ",
   "                            xxxxxxxx      ",
   "                                          ",
   "!!!!!!!!!!                    m           ",
   "!!!!!!!!!!        xxxxxx            m     ",
   "!!!!!!!!!!        o    x                  ",
   "!!!!!!!!!!        o    x!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxx",
   "                        x                 ",
   "                 !      x                 ",
   "            m    !      x       xxxxxxxxmx",
   "      m          !      x       x       m ",
   "                 !      x       x       m ",
   "  m       m                     x         ",
   "                              xxx   xxxxxx",
   "                 l              x         ",
   "!!!!!!  !!!!!jjjxxxx            x         ",
   " x   !  !   x      x            x         ",
   " x   !  !   x      x            x         ",
   " x   !  !   x      xxxxxxxxxxxxxxxxxxx    ",
   " x   !  !   x            vvx              ",
   " x          x              x              ",
   " x          x              x              ",
   " x          x              x    xxxxxxxxxx",
   " x          x              x              ",
   " x    ======x              x              ",
   " x                xxxxxx   x!!!           ",
   " x                o    x                  ",
   " x                o    x         !!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"], 
   
   
  ["                                          ",
   "                                          ",
   " @                                        ",
   "xxxxxxxxx                                 ",
   "xxxxxxxxx                                 ",
   "xxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxx",
   "                  x    x                  ",
   "          ========x    x========          ",
   "                  x    x                  ",
   "            x     x    x     x            ",
   "            x     x    x     x            ",
   "            x  l  x    x  m  x            ",
   "xxxxxxx     xxxxxxx    xxxxxxx     xxxxxxx",
   "                                          ",
   "                                          ",
   "                                          ",
   "xxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxx",
   "                                          ",
   "           m                  m           ",
   "     m           jjjjjjjj           m     ",
   "                                          ",
   "                                          ",
   "       !!!!!!!!!!!!!!!!!!!!!!!!!!!!       ",
   "       !!!!!!!!!!!!!!!!!!!!!!!!!!!!       ",
   "     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "              =   x    x   =              ",
   "              =   x    x   =              ",
   "              =   x    x   =              ",
   "              =   x    x   =              ",
   "                 !x    o                  ",
   "                 !x    o                  ",
   "xxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxx",
   "          x                    x          ",
   "          x                    x          ",
   "          x         jj         x          ",
   "          x                    x          ",
   "          x                    x          ",
   "          x!!!!    !!!!!!!!!!!!x          ",
   "          x                    x          ",
   "          x                    x          ",
   "          x    m               x          ",
   "          x                    x          ",
   "          x           m        x          ",
   "          x                    x          ",
   "          x             =======x          ",
   "          x                    x          ",
   "          x                    x          ",
   "xxxxxxxxxxx                    xxxxxxxxxxx",
   "                                          ",
   "                                          ",
   "                  xxxxxx                  ",
   "                  o    x                  ",
   "                  o    x                  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"], 
   
   
  ["                                          ",
   "                                          ",
   " @                                        ",
   "xxxxxxxxx                                 ",
   "xxxxxxxxx                                 ",
   "xxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxx",
   "                  x    x                  ",
   "                  x    x                  ",
   "                xx      xx                ",
   "               x          x               ",
   "              x            x              ",
   "              x            x              ",
   "   xxxxxxxxxxx         xxxxxxxxxxxxxxxx   ",
   "   x                l  x              x   ",
   "   x                   x              x   ",
   "   x             xxxxxxx       l      x   ",
   "   x             x                    x   ",
   "   x      xxxxxxxx          xxxx      x   ",
   "   x      x   x            x   x      x   ",
   "   x      x   x            x   x      x   ",
   "   x      x    x          x    x      x   ",
   "   x      x     xx      xx     x      x   ",
   "   x!!    x       x    x       x      x   ",
   "   x      x       x    x       x m    x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       xx   x       x      x   ",
   "   x  !!! x       x    x       x      x   ",
   "   x      x       x    x       x   m  x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x jjjx       x      x   ",
   "   x m    x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x  !   x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       xmm    x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x    ! x       x    x       x      x   ",
   "   x      x       x    x       x m    x   ",
   "   x      x       xj  xx       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x !!   x       x    x       x   m  x   ",
   "   x      x       x    x       x      x   ",
   "   x    m x       x    x       x      x   ",
   "   x      x       xxxj x       xmmm   x   ",
   "   x      x       x    x       x      x   ",
   "   x    m x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x!!!   x       x    x       x    m x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x  m   x       x    x       x      x   ",
   "   x      x       x   xx       x m    x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x =    x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x  x x       x      x   ",
   "   x   =  x       x    x       x      x   ",
   "   x m    x       x   lx       x   m  x   ",
   "   x      x       x  jjx       x      x   ",
   "   x!   !!x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       xxx  x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       xxx  x       x  m   x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      x       x    x       x      x   ",
   "   x      xxxxxxxxxx   x       x      x   ",
   "   x              o    x       x      x   ",
   "   x              o    x       x     mx   ",
   "   xxxxxxxxxxxxxxxxxxxxx       x      x   ",
   "                                          ",
   "                                          ",
   "                                          ",
   "                                          ",
   "                  xxxxxx                  ",
   "                  o    x                  ",
   "                  o    x   ==      ====   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   
  
  ["                                          ",
   "                                          ",
   "     x   x  xxx  x   x                    ",
   "     x   x xmmmx x   x                    ",
   "     x   x xlllx x   x                    ",
   "      xxx  xmmmx x   x                    ",
   "       x   xlllx x   x                    ",
   "       x   xmmmx x   x                    ",
   "       x   xl@lx x   x                    ",
   "       x    xxx   xxx                     ",
   "                                          ",
   "     x   x xxxxx x   x                    ",
   "     x   x   x   xx  x                    ",
   "     x   x   x   xx  x                    ",
   "     x   x   x   x x x                    ",
   "     x   x   x   x x x                    ",
   "     x x x   x   x  xx                    ",
   "     x x x   x   x  xx                    ",
   "      x x  xxxxx x   x                    ",
   "                                          ",
   "                                          ",
   "                                         o"]
   
   
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
